BUGFIX: judge nil pointer stored in error interface
uber-go/zap pull request #867
Opened 2020-09-24 09:40 UTC by FMLS

`
type T struct {

}

func (t T) Error() string {
	return ""
}

var n *T = nil

// false
log.Println(zap.Field("nil", n).Type == zapcore.ErrorType)
// will panic
log.Info("panic", mxlog.Field("nil", n))

`

2020-09-24 09:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber-go/zap?pullRequest=867) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber-go/zap?pullRequest=867) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber-go/zap?pullRequest=867) it.</sub>

2020-10-06 17:14 UTC, prashantv requested changes
Thank you for the contribution @FMLS 

Using `reflect` check for `nil` isn't always right, as it's possible to have a `nil` value that implements the `error` interface,
https://play.golang.org/p/5T8S35zdGsH

To handle nil in this case, please follow the same logic used by `Stringer` to detect a nil panic (which uses `recover`, similar to the standard library).

2020-11-24 18:33 UTC, abhinav commented on zapcore/field.go
> +		if rerr := recover(); rerr != nil {
can we undo this rename?

```suggestion
		if err := recover(); err != nil {
```

2020-11-24 18:33 UTC, abhinav commented on zapcore/field.go
> +			retErr = fmt.Errorf("PANIC=%v", rerr)
```suggestion
			retErr = fmt.Errorf("PANIC=%v", err)
```

2020-11-24 18:33 UTC, abhinav commented on zapcore/error.go
> +		retErr = enc.AddArray(key+"Causes", errArray(e.Errors()))
we don't need to do this. the defer and the named return will still capture the value.

```suggestion
		return enc.AddArray(key+"Causes", errArray(e.Errors()))
```

2020-11-24 18:33 UTC, abhinav commented on zapcore/error.go
> +	return retErr
```suggestion
	return nil
```

2020-11-24 18:33 UTC, abhinav commented on zapcore/error.go
> +			// Stringer that fails to guard against nil or a nil pointer for a
```suggestion
			// error that fails to guard against nil or a nil pointer for a
```

2020-11-24 18:35 UTC, abhinav commented on error.go
>  )
this doesn't need to change

```suggestion
	"sync"

	"go.uber.org/zap/zapcore"
)
```

2020-11-24 18:41 UTC, abhinav approved these changes

2020-11-24 18:46 UTC, prashantv approved these changes

2020-11-24 19:15 UTC, merged