Adding code to run on Powersystem
uber-go/zap pull request #872
Opened 2020-10-27 16:29 UTC by genisysram

Hi
Here is my contribution to your code, its working good on powersystems.

Thanks for the code, its working good.
## What do these changes do?
Added Architecture "ppc64le"
## Are there changes in behavior for the user?
No

2020-10-27 16:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber-go/zap?pullRequest=872) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber-go/zap?pullRequest=872) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber-go/zap?pullRequest=872) it.</sub>

2020-12-09 17:20 UTC, genisysram commented
@abhinav
Hi abinav 
please merge my PR

2020-12-09 19:14 UTC, abhinav requested changes
This doesn't look like it does what we want.

Looking at the build logs, we get the following 4 jobs:

```
$ go version
go version go1.11.13 linux/amd64

$ go version
go version go1.11.13 linux/ppc64le

$ go version
go version go1.13.15 linux/amd64

$ go version
go version go1.14.10 linux/amd64
```

I think we need to set the architecture in the matrix, not at the top-level.

2020-12-10 04:53 UTC, genisysram commented
@abhinav 
Thanks for correcting me , i made changes in a wrong place.

2020-12-10 18:39 UTC, abhinav approved these changes

2020-12-11 18:17 UTC, merged